### ISSUE TITLE
Poetry fails basic `install` behavior | Win 10 / v1.1.14

### ISSUE THREAD

**Issue by JPK85** [python-poetry/poetry#5997]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Windows 10 Version 21H2 OS build 19044.1766
- **Poetry version**: 1.1.14
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: [pyproject.toml](https://gist.github.com/JPK85/ef6a06d1dfc96aabd64fcaa05d9ac6f8)

## Issue

Poetry fails to install a new project created with `poetry new` (and any other attempted poetry project). Issue occurred right after updating to 1.1.14 from 1.1.13.

Tried deleting and reinstalling with [standard powershell installer from docs/master](https://python-poetry.org/docs/master/), problem persists.

### Objective / expected behavior

For now, I should hope to be able to run the most basic install command with any possible version of poetry.

### Steps to reproduce
With a freshly installed poetry 1.1.14:

1. `poetry new testpoetry`
2. `cd testpoetry`
3. `poetry install`

Results in the following behavior

```
Creating virtualenv testpoetry-g4SgMX0R-py3.8 in C:\Users\h18298\AppData\Local\pypoetry\Cache\virtualenvs

  AttributeError

  'PythonInfo' object has no attribute 'version_nodot'

  at ~\AppData\Roaming\pypoetry\venv\lib\site-packages\virtualenv\create\via_global_ref\builtin\cpython\cpython3.py:122 in python_zip
      118│         "python{VERSION}.zip" and "python{VERSION}._pth" files. User can
      119│         move/rename *zip* file and edit `sys.path` by editing *_pth* file.
      120│         Here the `pattern` is used only for the default *zip* file name!
      121│         """
    → 122│         pattern = "*python{}.zip".format(interpreter.version_nodot)
      123│         matches = fnmatch.filter(interpreter.path, pattern)
      124│         matched_paths = map(Path, matches)
      125│         existing_paths = filter(method("exists"), matched_paths)
      126│         path = next(existing_paths, None)
```

Tried on powershell & git bash, result is equal.

It seems poetry can no longer work with conda environments either, as it seems to be looking for the environment in the poetry virtualenvs folder (result is the same whether I'm on global python or active conda env). These problems occurred at the same time so I suspect they might be related.

On bash `poetry env info` shows no active environment at all:

```
Virtualenv
Python:         3.8.3
Implementation: CPython
Path:           NA
```

while on powershell it finds the active conda env/python:

```
Virtualenv
Python:         3.8.13
Implementation: CPython
Path:           C:\Users\<username>\Anaconda3\envs\testenv
Valid:          True
``` 

I tried updating to the --preview version as well, but that just gave a traceback and won't even start :) Here's hoping for some kind of advise!

Below find the full debug trace with `-vvv`:

```
poetry install -vvv                                                                            ❮  1s 251ms 

Creating virtualenv testpoetry-g4SgMX0R-py3.8 in C:\Users\<username>\AppData\Local\pypoetry\Cache\virtualenvs

  Stack trace:

  16  ~\AppData\Roaming\pypoetry\venv\lib\site-packages\clikit\console_application.py:131 in run
       129│             parsed_args = resolved_command.args
       130│
     → 131│             status_code = command.handle(parsed_args, io)
       132│         except KeyboardInterrupt:
       133│             status_code = 1

  15  ~\AppData\Roaming\pypoetry\venv\lib\site-packages\clikit\api\command\command.py:120 in handle
       118│     def handle(self, args, io):  # type: (Args, IO) -> int
       119│         try:
     → 120│             status_code = self._do_handle(args, io)
       121│         except KeyboardInterrupt:
       122│             if io.is_debug():

  14  ~\AppData\Roaming\pypoetry\venv\lib\site-packages\clikit\api\command\command.py:163 in _do_handle
       161│         if self._dispatcher and self._dispatcher.has_listeners(PRE_HANDLE):
       162│             event = PreHandleEvent(args, io, self)
     → 163│             self._dispatcher.dispatch(PRE_HANDLE, event)
       164│
       165│             if event.is_handled():

  13  ~\AppData\Roaming\pypoetry\venv\lib\site-packages\clikit\api\event\event_dispatcher.py:22 in dispatch
        20│
        21│         if listeners:
     →  22│             self._do_dispatch(listeners, event_name, event)
        23│
        24│         return event

  12  ~\AppData\Roaming\pypoetry\venv\lib\site-packages\clikit\api\event\event_dispatcher.py:89 in _do_dispatch
        87│                 break
        88│
     →  89│             listener(event, event_name, self)
        90│
        91│     def _sort_listeners(self, event_name):  # type: (str) -> None

  11  ~\AppData\Roaming\pypoetry\venv\lib\site-packages\poetry\console\config\application_config.py:119 in set_env
       117│
       118│         env_manager = EnvManager(poetry)
     → 119│         env = env_manager.create_venv(io)
       120│
       121│         if env.is_venv() and io.is_verbose():

  10  ~\AppData\Roaming\pypoetry\venv\lib\site-packages\poetry\utils\env.py:794 in create_venv
        792│             )
        793│
     →  794│             self.build_venv(venv, executable=executable)
        795│         else:
        796│             if force:

   9  ~\AppData\Roaming\pypoetry\venv\lib\site-packages\poetry\utils\env.py:835 in build_venv
        833│         if isinstance(executable, Path):
        834│             executable = executable.resolve().as_posix()
     →  835│         return virtualenv.cli_run(
        836│             [
        837│                 "--no-download",

   8  ~\AppData\Roaming\pypoetry\venv\lib\site-packages\virtualenv\run\__init__.py:30 in cli_run
        28│     """
        29│     env = os.environ if env is None else env
     →  30│     of_session = session_via_cli(args, options, setup_logging, env)
        31│     with of_session:
        32│         of_session.run()

   7  ~\AppData\Roaming\pypoetry\venv\lib\site-packages\virtualenv\run\__init__.py:48 in session_via_cli
        46│     """
        47│     env = os.environ if env is None else env
     →  48│     parser, elements = build_parser(args, options, setup_logging, env)
        49│     options = parser.parse_args(args)
        50│     creator, seeder, activators = tuple(e.create(options) for e in elements)  # create types

   6  ~\AppData\Roaming\pypoetry\venv\lib\site-packages\virtualenv\run\__init__.py:74 in build_parser
        72│         raise RuntimeError("failed to find interpreter for {}".format(discover))
        73│     elements = [
     →  74│         CreatorSelector(interpreter, parser),
        75│         SeederSelector(interpreter, parser),
        76│         ActivationSelector(interpreter, parser),

   5  ~\AppData\Roaming\pypoetry\venv\lib\site-packages\virtualenv\run\plugin\creators.py:15 in __init__
       13│ class CreatorSelector(ComponentBuilder):
       14│     def __init__(self, interpreter, parser):
     → 15│         creators, self.key_to_meta, self.describe, self.builtin_key = self.for_interpreter(interpreter)
       16│         super(CreatorSelector, self).__init__(interpreter, parser, "creator", creators)
       17│

   4  ~\AppData\Roaming\pypoetry\venv\lib\site-packages\virtualenv\run\plugin\creators.py:25 in for_interpreter
       23│             if key == "builtin":
       24│                 raise RuntimeError("builtin creator is a reserved name")
     → 25│             meta = creator_class.can_create(interpreter)
       26│             if meta:
       27│                 if meta.error:

   3  ~\AppData\Roaming\pypoetry\venv\lib\site-packages\virtualenv\create\via_global_ref\builtin\via_global_self_do.py:34 in can_create
        32│         meta = cls.setup_meta(interpreter)
        33│         if meta is not None and meta:
     →  34│             cls._sources_can_be_applied(interpreter, meta)
        35│         return meta
        36│

   2  ~\AppData\Roaming\pypoetry\venv\lib\site-packages\virtualenv\create\via_global_ref\builtin\via_global_self_do.py:39 in _sources_can_be_applied
        37│     @classmethod
        38│     def _sources_can_be_applied(cls, interpreter, meta):
     →  39│         for src in cls.sources(interpreter):
        40│             if src.exists:
        41│                 if meta.can_copy and not src.can_copy:

   1  ~\AppData\Roaming\pypoetry\venv\lib\site-packages\virtualenv\create\via_global_ref\builtin\cpython\cpython3.py:67 in sources
        65│                 cls.python_zip(interpreter),
        66│             )
     →  67│         for ref in refs:
        68│             yield ref
        69│

  AttributeError

  'PythonInfo' object has no attribute 'version_nodot'

  at ~\AppData\Roaming\pypoetry\venv\lib\site-packages\virtualenv\create\via_global_ref\builtin\cpython\cpython3.py:122 in python_zip
      118│         "python{VERSION}.zip" and "python{VERSION}._pth" files. User can
      119│         move/rename *zip* file and edit `sys.path` by editing *_pth* file.
      120│         Here the `pattern` is used only for the default *zip* file name!
      121│         """
    → 122│         pattern = "*python{}.zip".format(interpreter.version_nodot)
      123│         matches = fnmatch.filter(interpreter.path, pattern)
      124│         matched_paths = map(Path, matches)
      125│         existing_paths = filter(method("exists"), matched_paths)
      126│         path = next(existing_paths, None)
```

**Comment by JPK85** [comment]
I managed to sidestep the `install` specific issue by successfully upgrading to the --preview version (1.2.0b2) and changing the config variable `virtualenvs.prefer-active-python = false` to `true`, which seeks to pick up on the right environment.

Without the config fix the same error with the same stack trace repeats for the preview version as well. Same problem still persists with adding/updating certain packages (e.g., python-dotenv, pytest, pandas, openpyxl) -- it seems to successfully install these but keeps giving the same PythonInfo has no 'version_nodot' error. My confidence in this solution remains rather low!

**Comment by finswimmer** [comment]
Hello @JPK85,

I ran into this yesterday as well. In my case my conda `base` environment contained a python 3.8.3, after updating to 3.8.13 there and reinstall Poetry via the install script everything starts working again.

fin swimmer

**Comment by JPK85** [comment]
Thanks @finswimmer,

This started mysteriously working again through the miracle of time, so while it works I'd rather not mess with it more. Should the issue reappear I'll keep this fix in mind. Still no idea what the cause might be so it seems people might keep running into this.

-JP

**Comment by finswimmer** [comment]
Thanks for coming back to this. :+1: Because the issue seems to "solved" I will close it.

**Comment by earonesty** [comment]
this is still a bug.   it even has a nice stackoverflow page:  https://stackoverflow.com/questions/72970141/poetry-installs-adds-fail-with-pythoninfo-object-has-no-attribute-version-no

**Comment by Wingmore** [comment]
I have just encountered this same issue with poetry 1.2.1 and nothing I do seems to fix it...

Steps to reproduce:
1. `curl -sSL https://install.python-poetry.org --ssl-no-revoke | python - ` 
2. `poetry self update` or `poetry install` yeilds
'PythonInfo' object has no attribute 'version_nodot'

Additional Info
 `poetry --version`
Poetry (version 1.2.1)

`poetry env info`
```
Virtualenv
Python:         3.9.7
Implementation: CPython
Path:           NA
Executable:     NA

System
Platform:   win32
OS:         nt
Python:     3.9.7
Path:       C:\ProgramData\Anaconda3
Executable: C:\ProgramData\Anaconda3\python.exe
```

**Comment by neersighted** [comment]
I believe this is because does not support Anaconda formally (https://virtualenv.pypa.io/en/latest/installation.html#windows) -- and Poetry's installer will install into a regular virtualenv instead of a Conda environment.

If you want to open a FR for running Poetry on Conda, feel free -- however, this is not currently a Poetry issue as we do not support Anaconda as a platform for running Poetry on (we do support interoperating with Conda as an interpreter for your project, however).
