### PR TITLE
Require urllib3 ^1.26.0

### PR DESCRIPTION
**Pull request by davegaeddert**
I'm not actually sure how to make a test for this, but in debugging some other issues I found that [urllib3 needs to be at least version 1.26.0](
https://github.com/urllib3/urllib3/compare/1.25.11...1.26.0#diff-53a96dd57c993a39101318e9df47f8aab6610e8c2c1064f8109f66943dcbbd78R233) to use the `allowed_methods` parameter on the Retry class:

https://github.com/python-poetry/poetry/blob/7cc684981983963dc202e1a249a4b66667b468bd/src/poetry/publishing/uploader.py#L73

Or, it needs to continue using `method_whitelist` which is deprecated but not going to be removed until urllib3 v2.0... That would probably be safer in terms of restricting the downstream dependencies? Curious what you think. But maybe the restriction is ok considering people aren't screaming about `poetry publish` failing...

[This is where I first saw it.](https://github.com/dropseed/workhorse/runs/5159936470?check_suite_focus=true)
```sh
urllib3                1.25.8
...
   1  ~/.local/lib/python3.8/site-packages/poetry/publishing/uploader.py:106 in make_session
       104│         session.headers["User-Agent"] = self.user_agent
       105│         for scheme in ("http://", "https://"):
     → 106│             session.mount(scheme, self.adapter)
       107│ 
       108│         return session

  TypeError

  __init__() got an unexpected keyword argument 'allowed_methods'

  at ~/.local/lib/python3.8/site-packages/poetry/publishing/uploader.py:70 in adapter
       66│         return user_agent("poetry", __version__)
       67│ 
       68│     @property
       69│     def adapter(self) -> adapters.HTTPAdapter:
    →  70│         retry = util.Retry(
       71│             connect=5,
       72│             total=10,
       73│             allowed_methods=["GET"],
       74│             status_forcelist=[500, 501, 502, 503],
```

Probably introduced in #4580.

### CODE REVIEW

**Review by neersighted — APPROVED** [review]
Could you please rebase this to fix conflicts?

**Comment by abn** [comment]
@davegaeddert isin't the `urllib3` instance in question vendored by `requests` and not explicitly a top level dependency of poetry?

**Review by abn — APPROVED** [review]
