### ISSUE TITLE
cannot import name 'decode' from <venv>/poetry/core/utils/helpers.py

### ISSUE THREAD

**Issue by matroscoe** [python-poetry/poetry#8044]
- **Poetry version**: `1.5.1`/`1.4.2`
- **Python version**: `3.11.3`
- **OS version and name**: Ubuntu Latest (GitHub CI) 
- **pyproject.toml**: Working on getting this to you but the line that is causing an issue is: 
  ``` toml
  [tool.poetry.group.dev.dependencies]
  ...
  poetry = "^1.3.2"
  ```
- **Note:** This issue is only showing up it GitHub CI local runs are not seeing this problem.

- [X] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) stable Poetry version, installed using a recommended method.
- [X] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [X] I have consulted the [FAQ](https://python-poetry.org/docs/faq/) and [blog](https://python-poetry.org/blog/) for any relevant entries or release notes.
- [X] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option) and have included the output below.

## Issue
All builds or installs requiring poetry are returning the following exception when running in a GitHub CI run. 

```shell
cannot import name 'decode' from 'poetry.core.utils.helpers' (/opt/hostedtoolcache/Python/3.11.3/x64/lib/python3.11/site-packages/poetry/core/utils/helpers.py)
Error: Process completed with exit code 1.
```

**Comment by ralbertazzi** [comment]
I can't reproduce it. This works for me on Poetry 1.5.1 (system-wide) and installs Poetry 1.5.1 (which satisfies the `^1.3.2` constraint) inside the virtual environment.

```toml
[tool.poetry]
name = "test"
version = "0.1.0"
description = "test"
authors = ["Riccardo Albertazzi <email@email.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "~3.9"

[tool.poetry.group.dev.dependencies]
poetry = "^1.3.2"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
```

I'm getting the feeling that I didn't properly understand what you are trying to achieve. I suggest you to try providing a more complete example and clarification on what you want to install, otherwise I feel there's no other choice than closing this issue.

**Comment by matroscoe** [comment]
We are having the exact same problem, it works in version `1.4.2` and `1.5.1` locally but when we use it in a GitHub Action it fails with the error reported above. 

``` shell
Run poetry install
  poetry install
  shell: /usr/bin/bash -e {0}
  env:
    pythonLocation: /opt/hostedtoolcache/Python/3.11.3/x64
    PKG_CONFIG_PATH: /opt/hostedtoolcache/Python/3.11.3/x64/lib/pkgconfig
    Python_ROOT_DIR: /opt/hostedtoolcache/Python/3.11.3/x64
    Python[2](https://github.com/first-mode/<repo-name>/actions/runs/<run-id>/jobs/<job-id>#step:5:2)_ROOT_DIR: /opt/hostedtoolcache/Python/[3](https://github.com/first-mode/<repo-name>/actions/runs/<run-id>/jobs/<job-id>#step:5:3).11.3/x6[4](https://github.com/first-mode/<repo-name>/actions/runs/<run-id>/jobs/<job-id>#step:5:4)
    Python3_ROOT_DIR: /opt/hostedtoolcache/Python/3.11.3/x64
    LD_LIBRARY_PATH: /opt/hostedtoolcache/Python/3.11.3/x64/lib
Skipping virtualenv creation, as specified in config file.
Updating dependencies
Resolving dependencies...

Writing lock file

...
Updating poetry (1.2.2 -> 1.5.1)
...

Installing the current project: <package-name> (<package-version>)

cannot import name 'decode' from 'poetry.core.utils.helpers' (/opt/hostedtoolcache/Python/3.11.3/x64/lib/python3.11/site-packages/poetry/core/utils/helpers.py)
Error: Process completed with exit code 1.
```

**Comment by dimbleby** [comment]
> We are having the exact same problem

You are having the same problem as yourself?!

 `decode()` is right there - https://github.com/python-poetry/poetry-core/blob/bfab21efc0aa9b52657a8fcfc7164970a71c42db/src/poetry/core/utils/helpers.py#L31.

You checked the box declaring that you installed poetry using one of the recommended methods: but declaring a dependeny on poetry inside your pyproject.toml is absolutely not one of those.  Generally having poetry update its own environment like this is a bad idea.  

Please follow the poetry docs regarding installation, and close this issue.

**Comment by matroscoe** [comment]
I meant we were having the same issue as @ralbertazzi that we can only reproduce the issue in GitHub CI not locally, I was not aware of that issue and we will remove poetry as a requirement from our `pyproject.toml` files!

**Comment by matroscoe** [comment]
I cannot find the root cause of the issue but it has been isolated to a specific repository so I am closing this as I am not seeing the problem in any of our other repositories that are configured the same way.

**Comment by css-optivoy** [comment]
We've also been consistently getting this failure on our Github Actions lately, but I don't think it's an issue with Actions.
Initially we were only getting this on Actions, but I've since been able to reproduce it locally, and I've made the below minimal repro.
I suspect the critical part is poetry updating itself 1.5.0 -> 1.5.1, while it's running.

```bash
conda env create -f env.yml
conda activate test_env
poetry lock
poetry install -vvv
```

`env.yml`:
```yaml
name: test_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10.6
  - poetry=1.5.0
```

`pyproject.toml`:
```toml
[tool.poetry]
name = "test"
version = "0.1.0"
description = ""
authors = ["Me"]
packages = [
    { include = "test" },
    { include = "test/**/*.py" },
]

[tool.poetry.dependencies]
python = "3.10.6"
poetry = "1.5.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
```

`test/test.py`:
```python
```

This produces the following output (truncated to be slightly less verbose):
```
Updating dependencies
Resolving dependencies... (2.2s)

Writing lock file
Loading configuration file /home/css/.config/pypoetry/config.toml
Loading configuration file /home/css/.config/pypoetry/auth.toml
Using virtualenv: /home/css/miniconda3/envs/test_env
Installing dependencies from lock file

Finding the necessary packages for the current system

Package operations: 0 installs, 44 updates, 0 removals, 3 skipped

  • Updating pycparser (2.21 /home/conda/feedstock_root/build_artifacts/pycparser_1636257122734/work -> 2.21): Pending...
[keyring.backend] Loading KWallet
[keyring.backend] Loading SecretService
[keyring.backend] Loading Windows
[keyring.backend] Loading chainer
[keyring.backend] Loading libsecret
[keyring.backend] Loading macOS
Creating new session for pypi.org
[...]
  • Updating poetry-core (1.6.0 /home/conda/feedstock_root/build_artifacts/poetry-core_1684085122927/work -> 1.6.1): Pending...
  • Updating poetry-core (1.6.0 /home/conda/feedstock_root/build_artifacts/poetry-core_1684085122927/work -> 1.6.1): Installing...
[...]
  • Updating virtualenv (20.23.1 /home/conda/feedstock_root/build_artifacts/virtualenv_1687005325630/work -> 20.23.1): Pending...
  • Updating virtualenv (20.23.1 /home/conda/feedstock_root/build_artifacts/virtualenv_1687005325630/work -> 20.23.1): Installing...
  • Updating virtualenv (20.23.1 /home/conda/feedstock_root/build_artifacts/virtualenv_1687005325630/work -> 20.23.1)
  • Installing certifi (2023.5.7): Pending...
  • Installing certifi (2023.5.7): Skipped for the following reason: Already installed
  • Installing lockfile (0.12.2): Pending...
  • Installing lockfile (0.12.2): Skipped for the following reason: Already installed
  • Updating poetry (1.5.0 /home/conda/feedstock_root/build_artifacts/poetry_1684508323352/work -> 1.5.1): Pending...
  • Updating poetry (1.5.0 /home/conda/feedstock_root/build_artifacts/poetry_1684508323352/work -> 1.5.1): Installing...
  • Updating poetry (1.5.0 /home/conda/feedstock_root/build_artifacts/poetry_1684508323352/work -> 1.5.1)
  • Installing webencodings (0.5.1): Pending...
  • Installing webencodings (0.5.1): Skipped for the following reason: Already installed

Installing the current project: test (0.1.0)
  - Building package test in editable mode
  - Adding test.pth to /home/css/miniconda3/envs/test_env/lib/python3.10/site-packages for /home/css/tmp/env

  Stack trace:

  10  ~/miniconda3/envs/test_env/lib/python3.10/site-packages/cleo/application.py:327 in run
       325│ 
       326│             try:
     → 327│                 exit_code = self._run(io)
       328│             except BrokenPipeError:
       329│                 # If we are piped to another process, it may close early and send a

   9  ~/miniconda3/envs/test_env/lib/python3.10/site-packages/poetry/console/application.py:190 in _run
       188│         self._load_plugins(io)
       189│ 
     → 190│         exit_code: int = super()._run(io)
       191│         return exit_code
       192│ 

   8  ~/miniconda3/envs/test_env/lib/python3.10/site-packages/cleo/application.py:431 in _run
       429│             io.input.interactive(interactive)
       430│ 
     → 431│         exit_code = self._run_command(command, io)
       432│         self._running_command = None
       433│ 

   7  ~/miniconda3/envs/test_env/lib/python3.10/site-packages/cleo/application.py:473 in _run_command
       471│ 
       472│         if error is not None:
     → 473│             raise error
       474│ 
       475│         return terminate_event.exit_code

   6  ~/miniconda3/envs/test_env/lib/python3.10/site-packages/cleo/application.py:457 in _run_command
       455│ 
       456│             if command_event.command_should_run():
     → 457│                 exit_code = command.run(io)
       458│             else:
       459│                 exit_code = ConsoleCommandEvent.RETURN_CODE_DISABLED

   5  ~/miniconda3/envs/test_env/lib/python3.10/site-packages/cleo/commands/base_command.py:119 in run
       117│         io.input.validate()
       118│ 
     → 119│         status_code = self.execute(io)
       120│ 
       121│         if status_code is None:

   4  ~/miniconda3/envs/test_env/lib/python3.10/site-packages/cleo/commands/command.py:62 in execute
        60│ 
        61│         try:
     →  62│             return self.handle()
        63│         except KeyboardInterrupt:
        64│             return 1

   3  ~/miniconda3/envs/test_env/lib/python3.10/site-packages/poetry/console/commands/install.py:193 in handle
       191│             return 0
       192│ 
     → 193│         builder.build()
       194│ 
       195│         if overwrite:

   2  ~/miniconda3/envs/test_env/lib/python3.10/site-packages/poetry/masonry/builders/editable.py:80 in build
        78│         added_files += self._add_pth()
        79│         added_files += self._add_scripts()
     →  80│         self._add_dist_info(added_files)
        81│ 
        82│         path = self._path

   1  ~/miniconda3/envs/test_env/lib/python3.10/site-packages/poetry/masonry/builders/editable.py:212 in _add_dist_info
       210│ 
       211│     def _add_dist_info(self, added_files: list[Path]) -> None:
     → 212│         from poetry.core.masonry.builders.wheel import WheelBuilder
       213│ 
       214│         added_files = added_files[:]

  ImportError

  cannot import name 'decode' from 'poetry.core.utils.helpers' (/home/css/miniconda3/envs/test_env/lib/python3.10/site-packages/poetry/core/utils/helpers.py)

  at ~/miniconda3/envs/test_env/lib/python3.10/site-packages/poetry/core/masonry/builders/wheel.py:30 in <module>
       26│ from poetry.core.masonry.builders.sdist import SdistBuilder
       27│ from poetry.core.masonry.utils.helpers import distribution_name
       28│ from poetry.core.masonry.utils.helpers import normalize_file_permissions
       29│ from poetry.core.masonry.utils.package_include import PackageInclude
    →  30│ from poetry.core.utils.helpers import decode
       31│ from poetry.core.utils.helpers import temporary_directory
       32│ 
       33│ 
       34│ if TYPE_CHECKING:
```
